# This is a basic workflow to help you get started with Actions

name: SpringText CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macOS_5_2:
    name: Test macOS (5.2)
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: macOS (5.2)
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "SpringText.xcodeproj" -scheme "SpringText iOS" -destination "platform=iOS" clean test | xcpretty
